### ISSUE TITLE
Using BAL tool on ArcMap 10.6.1

### ISSUE THREAD

**Issue by hshearer55** [GeoscienceAustralia/BAL#19]
Have added Pythonpath to C:Python2.7, etc; tool still won't run. Ran unit tests through cmd (admin), some tests work (not all). Error message via Arcmap
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.6\BAL-2.1.2\bal.py", line 371, in <module>
    run()
  File "C:\Python27\ArcGIS10.6\BAL-2.1.2\bal.py", line 357, in run
    mask = find_aoi(extent, dem, veg)
  File "C:\Python27\ArcGIS10.6\BAL-2.1.2\bal.py", line 317, in find_aoi
    get_extent_mask(extent, mask)
  File "C:\Python27\ArcGIS10.6\BAL-2.1.2\bal.py", line 247, in get_extent_mask
    array.add(arcpy.Point(float(extent_list[0]), float(extent_list[1])))
ValueError: could not convert string to float: None

Failed to execute (BAL).

**Comment by wcarthur** [comment]
Hi @hshearer55 - noted. We're not actively developing the toolbox at present, but are aware that it's still tied to ArcGIS10.2 (and Python 2, which is now deprecated). Should resources become available, we'll be working on upgrading appropriately.
