### ISSUE TITLE
Input datasets must be in same folder

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/BAL#6]
Input DEM and classified vegetation raster layers **must** be in the same directory. This is documented, but it would be easier to remove this dependency on the location of the input data.

Traceback generated when DEM and vegetation data are in different directories:

```Traceback (most recent call last):
  File "C:\WorkSpace\bal\bal.py", line 370, in <module>
    run()
  File "C:\WorkSpace\bal\bal.py", line 356, in run
    mask = find_aoi(extent, dem, veg)
  File "C:\WorkSpace\bal\bal.py", line 308, in find_aoi
    arcpy.Intersect_analysis([dem_poly, veg_poly], mask)
  File "c:\program files (x86)\arcgis\desktop10.2\arcpy\arcpy\analysis.py", line 317, in Intersect
    raise e
ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Features: Dataset dem_poly.shp #;C:\WorkSpace\bal\examples\input\veg_poly.shp # does not exist or is not supported
Failed to execute (Intersect).


Failed to execute (BAL).

**Comment by wcarthur** [comment]
Resolved in #7
